language: android
android:
        components:
                - platform-tools
                - build-tools-26
                - android-26
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
- master